language: node_js

node_js: stable

cache:
  yarn: true

install: yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOY_TOKEN
  local-dir: dist
  verbose: true
  on:
    branch: master